# Generated by Django 4.2.4 on 2023-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('matrialtype', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=500)),
                ('myfile', models.FileField(upload_to='')),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('newstext', models.CharField(max_length=1000)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
