# Generated by Django 4.2.4 on 2023-10-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='matrialtype',
            new_name='materialtype',
        ),
    ]
