# Generated by Django 4.2.4 on 2023-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sturesponse',
            name='contactno',
            field=models.CharField(max_length=50),
        ),
    ]
